---
title: "Final Project Work"
author: "Lainey Newman"
date: "4/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(tidycensus)
library(skimr)
library(janitor)
library(readxl)
```


```{r}

state_unions <- read_excel("State_Union_Membership_Density_1964-2018.xlsx") %>%
  clean_names()

state_president <- read_csv("1976-2016-president.csv") %>%
  clean_names()

 state_unions <- state_unions %>%
   pivot_longer(cols = c(percent_mem18, percent_mem17, percent_mem16, percent_mem15, percent_mem14, percent_mem13, percent_mem12, percent_mem11, percent_mem10, percent_mem09, percent_mem08, percent_mem07, percent_mem06, percent_mem05, percent_mem04, percent_mem03, percent_mem02, percent_mem01, percent_mem00, percent_mem99, percent_mem98, percent_mem97, percent_mem96, percent_mem95, percent_mem94, percent_mem93, percent_mem92, percent_mem91, percent_mem90, percent_mem89, percent_mem88, percent_mem87, percent_mem86, percent_mem85, percent_mem84, percent_mem83, percent_mem82, percent_mem81, percent_mem80, percent_mem79, percent_mem78, percent_mem77, percent_mem76, percent_mem75, percent_mem74, percent_mem73, percent_mem72, percent_mem71, percent_mem70, percent_mem69, percent_mem68, percent_mem67, percent_mem66, percent_mem65, percent_mem64),
   names_to = "year", 
   values_to = "number_members") %>%
   na.omit()

state_unions <- state_unions %>%
  mutate(year_clean = str_replace(year, pattern = "percent_mem", replacement = "mem")) %>%
  mutate(state = state_name)
  
state_unions$year_clean <- state_unions$year_clean %>%
  str_replace(pattern = "mem1", replacement = "201") %>%
  str_replace(pattern = "mem0", replacement = "200") %>%
  str_replace(pattern = "mem6", replacement = "196") %>%
  str_replace(pattern = "mem7", replacement = "197") %>%
  str_replace(pattern = "mem8", replacement = "198") %>%
  str_replace(pattern = "mem9", replacement = "199")

state_president <- as.data.frame(state_president)
state_unions <- as.data.frame(state_unions)

state_unions$year <- as.numeric(state_unions$year_clean)

data <- left_join(state_president, state_unions, by = c("year", "state"),  
                  values_drop_na = TRUE)

class(state_president$state)
class(state_unions$state)
class(state_president$year)
class(state_unions$year)

data <- data %>%
  select(year, state, state_po, candidate, party, candidatevotes, totalvotes, number_members) %>%
  filter(party == "democrat" | party == "republican") %>%
  mutate(prop_votes = candidatevotes / totalvotes) %>%
  group_by(party, year) %>%
  mutate(mean_votes = mean(prop_votes)) %>%
  ungroup() %>%
  group_by(year) %>%
  mutate(avg_members = mean(number_members)) %>%
  ungroup() %>%
  group_by(year) %>%
  mutate(correlation = cor(prop_votes, number_members)) %>%
  mutate(decade = case_when(year <= 1979 ~ "1970s",
                            year > 1979 & year <= 1988 ~ "1980s", 
                            year > 1989 & year <= 1999 ~ "1990s",
                            year > 1999 & year <= 2009 ~ "2000s",
                            year > 2009 ~ "2010s"))
  

plot1 <- ggplot(data, aes(x = year, y = mean_votes, color = party)) + geom_line()

plot1

plot2 <- ggplot(data, aes(x = year, y = avg_members)) + geom_line()

plot2

```


```{r}

plot3data <- data %>%
  filter(party == "democrat") %>%
  ungroup(year) %>%
  group_by(state)

state_vector <- unique(plot3data$state)

plot3 <- ggplot(plot3data, aes(x = year)) + 
  geom_line(aes(y = number_members, color = "Union Density")) + 
  geom_line(aes(y = prop_votes * 100, color = "Democratic Vote Share")) +
  labs(y = "Percent") + ggtitle("Alabama")

plot3

```



```{r}

regression <- lm(prop_votes ~ number_members, data = data)

plot4 <- ggplot(data, aes(x = year, y = correlation)) + geom_line()

plot4

plot5 <- ggplot(data, aes(x = number_members, y = prop_votes)) + 
  geom_point() + 
  geom_smooth(method = "lm") 

plot5

plot6 <- ggplot(data, aes(x = number_members, y = prop_votes)) + 
  geom_point() + 
  geom_smooth(method = "lm") + facet_wrap( ~ decade)

plot6

```

plot5: slope of the line is 0 (coefficient of lm model is basically zero), means that there isn't really a correlation between the average number of members and prop votes. There is not a strong association between the variable of number of union members and the proportional vote share of Democrats. 

